name: assignment

services:
  app:
    build: ./app

  api:
    build: ./api
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}

  proxy:
    build: ./proxy
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"
    depends_on:
      - app
      - api
